// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converterimpl

import (
	v1 "github.com/jovulic/zfsilo/api/gen/go/zfsilo/v1"
	iface "github.com/jovulic/zfsilo/app/internal/converter/iface"
	database "github.com/jovulic/zfsilo/app/internal/database"
	datatypes "gorm.io/datatypes"
)

type HostConverterImpl struct{}

func (c *HostConverterImpl) FromAPIToDB(source *v1.Host) (*database.Host, error) {
	var pDatabaseHost *database.Host
	if source != nil {
		var databaseHost database.Host
		timeTime, err := iface.ConvertTimestampToTime((*source).CreateTime)
		if err != nil {
			return nil, err
		}
		databaseHost.CreateTime = timeTime
		timeTime2, err := iface.ConvertTimestampToTime((*source).UpdateTime)
		if err != nil {
			return nil, err
		}
		databaseHost.UpdateTime = timeTime2
		databaseHost.ID = (*source).Id
		databaseHost.Name = (*source).Name
		databaseHost.Connection = iface.ConvertHostConnectionFromAPIToDB((*source).Connection)
		databaseHost.Identifiers = c.stringListToDatatypesJSONSlice((*source).Ids)
		databaseHost.Key = (*source).Key
		databaseHost.ByConfig = (*source).ByConfig
		databaseHost.Role = iface.ConvertHostRoleFromAPIToDB((*source).Role)
		pDatabaseHost = &databaseHost
	}
	return pDatabaseHost, nil
}
func (c *HostConverterImpl) FromAPIToDBList(source []*v1.Host) ([]*database.Host, error) {
	var pDatabaseHostList []*database.Host
	if source != nil {
		pDatabaseHostList = make([]*database.Host, len(source))
		for i := 0; i < len(source); i++ {
			pDatabaseHost, err := c.FromAPIToDB(source[i])
			if err != nil {
				return nil, err
			}
			pDatabaseHostList[i] = pDatabaseHost
		}
	}
	return pDatabaseHostList, nil
}
func (c *HostConverterImpl) FromDBToAPI(source *database.Host) (*v1.Host, error) {
	var pZfsilov1Host *v1.Host
	if source != nil {
		var zfsilov1Host v1.Host
		pTimestamppbTimestamp, err := iface.ConvertTimeToTimestamp((*source).CreateTime)
		if err != nil {
			return nil, err
		}
		zfsilov1Host.CreateTime = pTimestamppbTimestamp
		pTimestamppbTimestamp2, err := iface.ConvertTimeToTimestamp((*source).UpdateTime)
		if err != nil {
			return nil, err
		}
		zfsilov1Host.UpdateTime = pTimestamppbTimestamp2
		zfsilov1Host.Id = (*source).ID
		zfsilov1Host.Name = (*source).Name
		zfsilov1Host.Connection = iface.ConvertHostConnectionFromDBToAPI((*source).Connection)
		zfsilov1Host.Ids = c.datatypesJSONSliceToStringList((*source).Identifiers)
		zfsilov1Host.Key = (*source).Key
		zfsilov1Host.ByConfig = (*source).ByConfig
		zfsilov1Host.Role = iface.ConvertHostRoleFromDBToAPI((*source).Role)
		pZfsilov1Host = &zfsilov1Host
	}
	return pZfsilov1Host, nil
}
func (c *HostConverterImpl) FromDBToAPIList(source []*database.Host) ([]*v1.Host, error) {
	var pZfsilov1HostList []*v1.Host
	if source != nil {
		pZfsilov1HostList = make([]*v1.Host, len(source))
		for i := 0; i < len(source); i++ {
			pZfsilov1Host, err := c.FromDBToAPI(source[i])
			if err != nil {
				return nil, err
			}
			pZfsilov1HostList[i] = pZfsilov1Host
		}
	}
	return pZfsilov1HostList, nil
}
func (c *HostConverterImpl) datatypesJSONSliceToStringList(source datatypes.JSONSlice[string]) []string {
	var stringList []string
	if source != nil {
		stringList = make([]string, len(source))
		for i := 0; i < len(source); i++ {
			stringList[i] = source[i]
		}
	}
	return stringList
}
func (c *HostConverterImpl) stringListToDatatypesJSONSlice(source []string) datatypes.JSONSlice[string] {
	var datatypesJSONSlice datatypes.JSONSlice[string]
	if source != nil {
		datatypesJSONSlice = make(datatypes.JSONSlice[string], len(source))
		for i := 0; i < len(source); i++ {
			datatypesJSONSlice[i] = source[i]
		}
	}
	return datatypesJSONSlice
}
