// Code generated by "stringer -type=HostRole -linecomment host.go"; DO NOT EDIT.

package database

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HostRoleUNSPECIFIED-0]
	_ = x[HostRoleSERVER-1]
	_ = x[HostRoleCLIENT-2]
}

const _HostRole_name = "UNSPECIFIEDSERVERCLIENT"

var _HostRole_index = [...]uint8{0, 11, 17, 23}

func (i HostRole) String() string {
	if i < 0 || i >= HostRole(len(_HostRole_index)-1) {
		return "HostRole(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HostRole_name[_HostRole_index[i]:_HostRole_index[i+1]]
}
