// Code generated by "stringer -type=VolumeStatus -linecomment volume.go"; DO NOT EDIT.

package database

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VolumeStatusUNSPECIFIED-0]
	_ = x[VolumeStatusINITIAL-1]
	_ = x[VolumeStatusPUBLISHED-2]
	_ = x[VolumeStatusCONNECTED-3]
	_ = x[VolumeStatusMOUNTED-4]
}

const _VolumeStatus_name = "UNSPECIFIEDINITIALPUBLISHEDCONNECTEDMOUNTED"

var _VolumeStatus_index = [...]uint8{0, 11, 18, 27, 36, 43}

func (i VolumeStatus) String() string {
	if i < 0 || i >= VolumeStatus(len(_VolumeStatus_index)-1) {
		return "VolumeStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VolumeStatus_name[_VolumeStatus_index[i]:_VolumeStatus_index[i+1]]
}
