// Code generated by "stringer -type=VolumeTransport -linecomment volume.go"; DO NOT EDIT.

package database

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VolumeTransportUNSPECIFIED-0]
	_ = x[VolumeTransportISCSI-1]
	_ = x[VolumeTransportNVMEOF_TCP-2]
}

const _VolumeTransport_name = "UNSPECIFIEDISCSINVMEOF_TCP"

var _VolumeTransport_index = [...]uint8{0, 11, 16, 26}

func (i VolumeTransport) String() string {
	if i < 0 || i >= VolumeTransport(len(_VolumeTransport_index)-1) {
		return "VolumeTransport(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VolumeTransport_name[_VolumeTransport_index[i]:_VolumeTransport_index[i+1]]
}
