// Code generated by "stringer -type=VolumeMode -linecomment volume.go"; DO NOT EDIT.

package database

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VolumeModeUNSPECIFIED-0]
	_ = x[VolumeModeBLOCK-1]
	_ = x[VolumeModeFILESYSTEM-2]
}

const _VolumeMode_name = "UNSPECIFIEDBLOCKFILESYSTEM"

var _VolumeMode_index = [...]uint8{0, 11, 16, 26}

func (i VolumeMode) String() string {
	if i < 0 || i >= VolumeMode(len(_VolumeMode_index)-1) {
		return "VolumeMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VolumeMode_name[_VolumeMode_index[i]:_VolumeMode_index[i+1]]
}
