version: "2"

linters:
  default: fast
  enable:
    - staticcheck
    - exhaustive
  disable:
    - depguard
    - wsl
    - nlreturn
    - godox
    - lll
    - mnd
    - cyclop
    - gocognit
    - funlen
    - prealloc
    - nestif
    - dupl
