run:
  go run -ldflags "-X 'main.Version=local'" . start --config ./config.json 

test:
  go test ./...

test_short:
  go test -short ./...

build:
  go build -tags "json1"

generate:
  go generate ./...
  sed -i "s/-mod=mod //g" wire_gen.go

wire:
  wire

lint:
  golangci-lint run
