// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/jovulic/zfsilo/app/internal/command"
	"github.com/jovulic/zfsilo/app/internal/config"
	"github.com/jovulic/zfsilo/app/internal/converter"
	"github.com/jovulic/zfsilo/app/internal/database"
	"github.com/jovulic/zfsilo/app/internal/service"
	"github.com/skovtunenko/graterm"
)

// Injectors from wire.go:

func WireApp(ctx context.Context, conf config.Config, term *graterm.Terminator) (*App, error) {
	serviceService := service.WireService()
	db, err := database.WireDatabase(ctx, conf)
	if err != nil {
		return nil, err
	}
	volumeConverter := converter.WireVolumeConverter()
	produceExecutor, err := command.WireProduceTarget(conf)
	if err != nil {
		return nil, err
	}
	consumeExecutorMap, err := command.WireConsumeTarget(conf)
	if err != nil {
		return nil, err
	}
	volumeService := service.WireVolumeService(db, volumeConverter, produceExecutor, consumeExecutorMap)
	server, err := service.WireServer(ctx, conf, term, serviceService, volumeService)
	if err != nil {
		return nil, err
	}
	app := NewApp(server)
	return app, nil
}
