// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/jovulic/zfsilo/csi/internal/config"
	"github.com/jovulic/zfsilo/csi/internal/service"
	"github.com/skovtunenko/graterm"
)

// Injectors from wire.go:

func WireApp(ctx context.Context, conf config.Config, term *graterm.Terminator) (*App, error) {
	csiService, err := service.WireCSIService(ctx, conf, term)
	if err != nil {
		return nil, err
	}
	server, err := service.WireServer(ctx, conf, term, csiService)
	if err != nil {
		return nil, err
	}
	app := NewApp(server)
	return app, nil
}
